
###Register new user
POST http://localhost:6070/api/user/register
Content-Type: application/json

{
"username":"joh",
"email":"joh@yahoo.com",
"password":"1234abcd"
}

###User login
POST http://localhost:6070/api/user/login
Content-Type: application/json

{
"username":"joh",
"email":"joh@yahoo.com",
"password":"1234abcd"
}

###Create task
POST http://localhost:6070/api/task/createTask
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWM3YjEyNjk2MDdlNDJkNTM1ZjQ3NSIsImlhdCI6MTY3OTU4ODEzNCwiZXhwIjoxNjc5NTkxNzM0fQ.ZP6mPPjMJ5CQty01KXMv_reJEHKZleKTPmaif6dUKfs

{
"title":"cook",
"description":"new recipe",
"completed":"false",
"dueDate":"27-03-2023"  
 }

###Get all tasks
GET http://localhost:6070/api/task/allTasks
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWM3YjEyNjk2MDdlNDJkNTM1ZjQ3NSIsImlhdCI6MTY3OTU4ODEzNCwiZXhwIjoxNjc5NTkxNzM0fQ.ZP6mPPjMJ5CQty01KXMv_reJEHKZleKTPmaif6dUKfs

###Get one task
GET http://localhost:6070/api/task/641c614515c193a4ff4ddda3
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWM2MGU4MTVjMTkzYTRmZjRkZGQ5YyIsImlhdCI6MTY3OTU4MTQzMSwiZXhwIjoxNjc5NTg1MDMxfQ.dsrOZm-jvpO-Ywj-KXJJodP6abCmUGn_1vpFRWQL6P4

###Delete a certain task
DELETE http://localhost:6070/api/task/delete/641c7b4169607e42d535f478
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWM3YjEyNjk2MDdlNDJkNTM1ZjQ3NSIsImlhdCI6MTY3OTU4ODEzNCwiZXhwIjoxNjc5NTkxNzM0fQ.ZP6mPPjMJ5CQty01KXMv_reJEHKZleKTPmaif6dUKfs

###Edit a certain task
PUT http://localhost:6070/api/task/edit/641c611a15c193a4ff4ddd9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWM2MGU4MTVjMTkzYTRmZjRkZGQ5YyIsImlhdCI6MTY3OTU4MTQzMSwiZXhwIjoxNjc5NTg1MDMxfQ.dsrOZm-jvpO-Ywj-KXJJodP6abCmUGn_1vpFRWQL6P4

{
"title":"movie",
"description":"new movie",
"completed":"true",
"dueDate":"25-03-2023"  
}

